version: "3"

services:
    test1:
        image: ubuntu
        container: ubuntu1
      
        networks:
        - network1
        - network2              
    test2:
        image: nginx
        container: nginx1
        port: ["8000"]
        networks:
        - network1
        - network2


networks:
  network1:
  network2:
  network3:
